**Задание 1** Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [3]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

**Задание 2.** Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [25]:
a1=a.reshape(2, 6)
print(a1)
a2=a.reshape(4, 3)
print(a2) #3 столбца и 4 строки
a3=a.reshape(6, 2)
print(a3) #2 столбца и 6 строк (наблюдения и значения разные в сравнении с 1) 
a4=a.reshape(3, 4)
print(a4)
a5=a.reshape(12, 1)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


**Задание 3.** Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [29]:
a1=a.reshape(4, -1)
print(a1)
a2=a.reshape(3, -1)
print(a2)
a3=a.reshape(-1, 3)
print(a3)
a4=a.reshape(-1, 4)
print(a4)
a5=a.reshape(-1, 6)
print(a5)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


**Задание 4** Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
**нет, из примеров выше массив a - одномерный, но, например, a5 - двумерный (1 столбец и 12 строк наблюдений)**

**Задание 5** Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [38]:
b=np.random.randn(3,4)
print(b)

b=b.flatten()
print(b)

[[ 1.3795748  -0.9207201  -0.04653483  0.31028443]
 [-0.56030083  1.93205831  1.13697713  0.97096639]
 [ 0.52121783  1.8610091   1.23633056 -0.63012128]]
12
[ 1.3795748  -0.9207201  -0.04653483  0.31028443 -0.56030083  1.93205831
  1.13697713  0.97096639  0.52121783  1.8610091   1.23633056 -0.63012128]


**Задание 6** Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [40]:
a=np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

**задание 7** Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [41]:
b=np.arange(20, 1, -2).reshape(1,10)
b #b - двумерный массив (предыдущий a - одномерный)

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

**Задание 8** Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [53]:
a = np.array(
    [[0, 0], 
    [0, 0]])
b = np.array(
    [[1, 1], 
    [1, 1],
    [1, 1]
    ])
c = np.vstack((a, b))
print(c)
print(c.size)

[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]]
10


**Задание 9** Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [60]:
a=np.arange(0, 12)
A=a.reshape(4,3)
At=A.T
B = np.dot(A, At)
print(B)
B.shape #размер B 4x4
#Вычислить обратную матрицу для матрицы B не получится, т.к. это вырожденная матрица (функция linalg LinAlgError: Singular matrix)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


(4, 4)

**Задание 10** Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [67]:
np.random.seed(42)

**Задание 11** Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [70]:
c=np.random.randint(0, 16,16)
c

array([11,  9,  5, 12, 11,  8,  0, 10, 10, 14,  9, 15, 11, 11, 15, 14])

**Задание 12** Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [76]:
C=c.reshape(4,4)
D=B+C*10
print(D)
d=np.linalg.det(D) #определитель
print(d)
r=np.linalg.matrix_rank(D)#ранг
print(r)
D_inv=np.linalg.inv(D)#обратная матрица
print(D_inv)

[[115 104  73 152]
 [124 130  86 222]
 [123 226 239 362]
 [142 232 362 442]]
62650800.0
4
[[ 0.01886552 -0.00325327 -0.01147599  0.00454519]
 [ 0.01683203 -0.02439777  0.02559361 -0.01449559]
 [ 0.01273886 -0.01565599 -0.00270994  0.00570208]
 [-0.02532897  0.02667356 -0.00752744  0.00374073]]


**Задание 13** риравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [77]:
D_inv=np.where(D_inv<0, 0,1)
D_inv

array([[1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 0, 1]])

In [78]:
E=np.where(D_inv==1, B, C)
E

array([[  5,   9,   5,  32],
       [ 14,   8,  86,  10],
       [ 23,  14,   9, 212],
       [ 11, 122,  15, 302]])